FROM node:21.0.0 as build

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:21.0.0

WORKDIR /app

COPY --from=build /app/build /app/build

RUN npm install -g serve

CMD ["serve", "-p", "80", "build"]