services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 8080:3000
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/app
            - /app/node_modules
        ports:
            - 8081:8081
    db:
        image: mongo:7.0.9
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017

volumes:
    mongodata:
