services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile.prod
        volumes:
            - nginx-logs:/app/logs
        ports:
            - 8080:8080
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        ports:
            - 8081:8081
    db:
        image: mongo:7.0.9
        volumes:
            - mongodata:/data/db
        ports:
            - 27017:27017

volumes:
    nginx-logs:
    mongodata:
