version: "3.3"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 3000:3000
