FROM node:21.0.0 as build

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client .
COPY ./client/.env.prod ./.env

RUN npm run build


FROM nginx:1.25.5

WORKDIR /app

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/build /app/build

CMD ["nginx", "-g", "daemon off;"]